### ISSUE TITLE
Deleting a image that have same name with an older one makes older one unusable

### ISSUE THREAD

**Issue by MustaphaTR** [DBolical/Home#32]
In fact if you try to do this, old image is showed for new image too. If you delete this with Delete button older image with same name possibly gets deleted from database. But an image link in Image section lasts there.

There are 2 images i did that mistake. There are links.
http://www.moddb.com/mods/red-alert-2-yuris-revenge-cncd2k-mod/images/ingame-screenshot-19#imagebox
http://www.moddb.com/mods/red-alert-2-yuris-revenge-cncd2k-mod/images/irish-heavy-tank#imagebox

I think if i try to upload a new picture with a same name of older. Image itself should be saved with different name too like image section page, or it should give error, "there is already a file named as _._". It is hard to remember was there a file named like this.

**Comment by intenscia** [comment]
This is an old bug when the system didn't enforce unique filenames. whilst it will continue to affect old images, I'm fairly certain you cannot replicate it now when uploading then deleting new images.
