### ISSUE TITLE
Review notifications

### ISSUE THREAD

**Issue by Marek33** [DBolical/Home#57]
I want to see when someone else posts a review of a game or a mod. In the 31 December I get a notification of a review, which had early access back then. Now when someone else posted a review (somewhere in a March 2016) I don't get any notification. I track both of those people and I want to have a notification of them like it was before.

**Comment by marth8880** [comment]
Yep, definitely agree with this.

**Comment by Marek33** [comment]
Its been two months and I get every notification so I think that I can close this.
