### ISSUE TITLE
Job resumes

### ISSUE THREAD

**Issue by feillyne** [DBolical/Home#67]
Job resumes subsection on the Jobs board. Could be closely tied to the member profiles, and one resume per one member account. Because right now sites such as DeviantArt greatly surpass us not only in member profile customisation but also professional presentation of members. Pretty convinced quite a few artists here would like to submit and present their qualifications, references etc. in an orderly fashion on their own member profiles (and freely open/close their status, whether they are available or unavailable for any jobs offered at the moment).

**Comment by marth8880** [comment]
Yes, would absolutely **love** this.

**Comment by feillyne** [comment]
Ahhh, this has already been suggested https://github.com/DBolical/Home/issues/9 so it is only a duplicate issue.
